# Dockerfile for pygeoapi WFS server
# Base image: official pygeoapi image (geopython project, OSGeo incubated)
FROM geopython/pygeoapi:latest

# ── Data files ────────────────────────────────────────────────────────────────
# Copy the source GeoJSON (pre-renamed copy to avoid Docker issues with spaces)
COPY cipa_sites.geojson /data/cipa_sites.geojson

# Copy the H3 stress-test GeoJSON (generated by generate_stress_test.py)
# Run `python generate_stress_test.py` before building this image.
COPY h3_stress_test.geojson /data/h3_stress_test.geojson

# ── Configuration ─────────────────────────────────────────────────────────────
COPY pygeoapi-config.yml /pygeoapi/local.config.yml

# pygeoapi reads these env vars to locate config + OpenAPI spec
ENV PYGEOAPI_CONFIG=/pygeoapi/local.config.yml
ENV PYGEOAPI_OPENAPI=/pygeoapi/openapi.yml

# ── Runtime ───────────────────────────────────────────────────────────────────
# The base image entrypoint generates openapi.yml automatically on startup.
EXPOSE 5000

# CMD is inherited from the base image: gunicorn serving pygeoapi
